create table address (address_id bigint not null auto_increment, address_first varchar(50), address_second varchar(100), default_address bit not null, test_field10 varchar(100), zip_code varchar(6), owner_member_number bigint not null, primary key (address_id));
create table cart (cart_id bigint not null auto_increment, created datetime, updated datetime, owner_member_number bigint not null, primary key (cart_id));
create table cart_item_list (cart_cart_id bigint not null, item_list_cart_item_id bigint not null, primary key (cart_cart_id, item_list_cart_item_id));
create table cart_item (cart_item_id bigint not null, order_quantity integer not null, cart_id bigint not null, sku_item_id bigint not null, primary key (cart_item_id));
create table category (category_id bigint not null, category_level integer, display_name varchar(255), parent_category_category_id bigint, primary key (category_id));
create table category_shop_list (category_category_id bigint not null, shop_list_shop_id bigint not null);
create table corporation (corporation_id bigint not null, corporation_name varchar(255), primary key (corporation_id));
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table member (member_number bigint not null auto_increment, email varchar(30) not null, member_id varchar(20) not null, member_name varchar(30) not null, member_status varchar(1) not null, member_type varchar(1) not null, password varchar(20) not null, affiliated_corporation_id bigint, actvie_cart_id bigint, primary key (member_number));
create table prd_prd_option (product_id varchar(255) not null, option_id bigint not null, primary key (product_id, option_id));
create table product (product_id varchar(255) not null, display_name varchar(255), product_name varchar(255), product_type integer, display_category_id bigint, primary key (product_id));
create table product_option (option_id bigint not null, display_name varchar(255), option_name varchar(255), primary key (option_id));
create table product_option_value (value_id bigint not null, display_name varchar(255), value varchar(255), target_option bigint not null, primary key (value_id));
create table shop (shop_id bigint not null, category_category_id bigint, primary key (shop_id));
create table sku (sku_id bigint not null, display_name varchar(255), retail_price bigint, sales_price bigint, stock bigint not null, product_id varchar(255), primary key (sku_id));
create table sku_prd_attr_value (sku_id bigint not null, value_id bigint not null);
alter table cart_item_list add constraint UK_48qc56omyiluvqdasrlloqi13 unique (item_list_cart_item_id);
alter table category_shop_list add constraint UK_a9ow60xtn60lqbrv2yc29w4oc unique (shop_list_shop_id);
alter table member add constraint UK_mbmcqelty0fbrvxp1q58dn57t unique (email);
alter table member add constraint UK_4rw879c4q7wrgi3v64cy73b17 unique (member_id);
alter table address add constraint FK298fmj38hmckkrepxnatspo2g foreign key (owner_member_number) references member (member_number);
alter table cart add constraint FK43pxlei27b2ecsy55r2gs4ymw foreign key (owner_member_number) references member (member_number);
alter table cart_item_list add constraint FKg512rdl5tff1qpn0xqk458sql foreign key (item_list_cart_item_id) references cart_item (cart_item_id);
alter table cart_item_list add constraint FK6j4m0i51v559xj6b5knt99vt8 foreign key (cart_cart_id) references cart (cart_id);
alter table cart_item add constraint FK1uobyhgl1wvgt1jpccia8xxs3 foreign key (cart_id) references cart (cart_id);
alter table cart_item add constraint FKcsmo04kwickg4x3dwlwbp64bp foreign key (sku_item_id) references sku (sku_id);
alter table category add constraint FKhyf0d7atqv1xg87nqp0hl6p4f foreign key (parent_category_category_id) references category (category_id);
alter table category_shop_list add constraint FK90uoguoqp0n3fqrayf6179ytu foreign key (shop_list_shop_id) references shop (shop_id);
alter table category_shop_list add constraint FKslmw44ehckuo6sk5ams3ekf4l foreign key (category_category_id) references category (category_id);
alter table member add constraint FKkp5dtv2w3vb4saju7cipu0ha0 foreign key (affiliated_corporation_id) references corporation (corporation_id);
alter table member add constraint FKnl8i27ix83ak18qfeuki84bgr foreign key (actvie_cart_id) references cart (cart_id);
alter table prd_prd_option add constraint FKgpw5jbn042nv7a52vmrsflcs8 foreign key (option_id) references product_option (option_id);
alter table prd_prd_option add constraint FKeivgdkk3f6sslrqptsk3r3fl1 foreign key (product_id) references product (product_id);
alter table product add constraint FKdcfjqt0esbinev25h7ykl861a foreign key (display_category_id) references category (category_id);
alter table product_option_value add constraint FKfywwxfxnrld4pne9nkfqgsogm foreign key (target_option) references product_option (option_id);
alter table shop add constraint FKjbynf9r06xowr0f9juf7j16et foreign key (category_category_id) references category (category_id);
alter table sku add constraint FKovd96qvc9da3k94gf0j822p3o foreign key (product_id) references product (product_id);
alter table sku_prd_attr_value add constraint FKl9gk53tg3g701fr1t90kocsk7 foreign key (value_id) references product_option_value (value_id);
alter table sku_prd_attr_value add constraint FK13qd7q505092mbtop370f6vqm foreign key (sku_id) references sku (sku_id);
